# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "virtio_pci" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FED2-E8B0";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/cache" = {
    device = "zroot/cache";
    fsType = "zfs";
  };

  fileSystems."/persist" = {
    device = "zroot/persist";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "zroot/nix";
    fsType = "zfs";
  };

  fileSystems."/var/lib/nixos" = {
    device = "/persist/var/lib/nixos";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/var/log" = {
    device = "/persist/var/log";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/kitty" = {
    device = "/cache/home/salivala/.cache/kitty";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/fontconfig" = {
    device = "/persist/home/salivala/.cache/fontconfig";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/dconf" = {
    device = "/persist/home/salivala/.cache/dconf";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/nix-search-tv" = {
    device = "/cache/home/salivala/.cache/nix-search-tv";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/nvf" = {
    device = "/cache/home/salivala/.cache/nvf";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/nvidia" = {
    device = "/cache/home/salivala/.cache/nvidia";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/spotify" = {
    device = "/cache/home/salivala/.cache/spotify";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/Vencord" = {
    device = "/persist/home/salivala/.config/Vencord";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/discord" = {
    device = "/persist/home/salivala/.config/discord";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/dconf" = {
    device = "/persist/home/salivala/.config/dconf";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/sops" = {
    device = "/persist/home/salivala/.config/sops";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/spotify" = {
    device = "/persist/home/salivala/.config/spotify";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/vesktop" = {
    device = "/persist/home/salivala/.config/vesktop";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/yazi" = {
    device = "/persist/home/salivala/.config/yazi";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.local/share/Steam" = {
    device = "/persist/home/salivala/.local/share/Steam";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.local/share/lutris" = {
    device = "/persist/home/salivala/.local/share/lutris";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.mozilla/firefox" = {
    device = "/persist/home/salivala/.mozilla/firefox";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.local/share/nvf" = {
    device = "/persist/home/salivala/.local/share/nvf";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.ssh" = {
    device = "/persist/home/salivala/.ssh";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.steam" = {
    device = "/persist/home/salivala/.steam";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.var/app/com.spotify.Client" = {
    device = "/persist/home/salivala/.var/app/com.spotify.Client";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/Downloads" = {
    device = "/persist/home/salivala/Downloads";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/Pictures" = {
    device = "/persist/home/salivala/Pictures";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/Projects" = {
    device = "/persist/home/salivala/Projects";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/Videos" = {
    device = "/persist/home/salivala/Videos";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/nixos-config" = {
    device = "/persist/home/salivala/nixos-config";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/var/lib/flatpak" = {
    device = "/persist/var/lib/flatpak";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/var/lib/systemd/coredump" = {
    device = "/persist/var/lib/systemd/coredump";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/tmp" = {
    device = "zroot/tmp";
    fsType = "zfs";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/c3056a05-4050-47b9-93ae-943068bb8c44";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
