# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4D6E-2774";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/cache" = {
    device = "zroot/cache";
    fsType = "zfs";
  };

  fileSystems."/persist" = {
    device = "zroot/persist";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "zroot/nix";
    fsType = "zfs";
  };

  fileSystems."/var/lib/nixos" = {
    device = "/persist/var/lib/nixos";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/var/log" = {
    device = "/persist/var/log";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/etc/NetworkManager/system-connections" = {
    device = "/persist/etc/NetworkManager/system-connections";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.ICAClient" = {
    device = "/persist/home/salivala/.ICAClient";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.audacity-data" = {
    device = "/persist/home/salivala/.audacity-data";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/dconf" = {
    device = "/persist/home/salivala/.cache/dconf";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/fish" = {
    device = "/cache/home/salivala/.cache/fish";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/kitty" = {
    device = "/cache/home/salivala/.cache/kitty";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/fontconfig" = {
    device = "/persist/home/salivala/.cache/fontconfig";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/mozilla" = {
    device = "/cache/home/salivala/.cache/mozilla";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/nix-search-tv" = {
    device = "/cache/home/salivala/.cache/nix-search-tv";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/noctalia" = {
    device = "/cache/home/salivala/.cache/noctalia";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/nvf" = {
    device = "/cache/home/salivala/.cache/nvf";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/nvidia" = {
    device = "/cache/home/salivala/.cache/nvidia";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/spotify" = {
    device = "/cache/home/salivala/.cache/spotify";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/spotify-player" = {
    device = "/cache/home/salivala/.cache/spotify-player";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.cache/zellij" = {
    device = "/cache/home/salivala/.cache/zellij";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/Citrix" = {
    device = "/persist/home/salivala/.config/Citrix";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/dconf" = {
    device = "/persist/home/salivala/.config/dconf";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/discord" = {
    device = "/persist/home/salivala/.config/discord";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/sops" = {
    device = "/persist/home/salivala/.config/sops";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/spotify" = {
    device = "/persist/home/salivala/.config/spotify";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/noctalia" = {
    device = "/persist/home/salivala/.config/noctalia";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/spotify-player" = {
    device = "/persist/home/salivala/.config/spotify-player";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/uhk-agent" = {
    device = "/persist/home/salivala/.config/uhk-agent";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/vencord" = {
    device = "/persist/home/salivala/.config/vencord";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/vesktop" = {
    device = "/persist/home/salivala/.config/vesktop";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/yazi" = {
    device = "/persist/home/salivala/.config/yazi";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/zed" = {
    device = "/persist/home/salivala/.config/zed";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.config/zellij" = {
    device = "/persist/home/salivala/.config/zellij";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.local/share/Citrix" = {
    device = "/persist/home/salivala/.local/share/Citrix";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.local/share/Steam" = {
    device = "/persist/home/salivala/.local/share/Steam";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.local/share/containers" = {
    device = "/persist/home/salivala/.local/share/containers";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.local/share/direnv" = {
    device = "/persist/home/salivala/.local/share/direnv";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.local/share/lutris" = {
    device = "/persist/home/salivala/.local/share/lutris";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.local/share/nvf" = {
    device = "/persist/home/salivala/.local/share/nvf";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.local/share/zed" = {
    device = "/persist/home/salivala/.local/share/zed";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.local/state/yazi" = {
    device = "/persist/home/salivala/.local/state/yazi";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.mozilla" = {
    device = "/persist/home/salivala/.mozilla";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.pki" = {
    device = "/persist/home/salivala/.pki";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.steam" = {
    device = "/persist/home/salivala/.steam";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.ssh" = {
    device = "/persist/home/salivala/.ssh";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/.var/app/com.spotify.Client" = {
    device = "/persist/home/salivala/.var/app/com.spotify.Client";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/Downloads" = {
    device = "/persist/home/salivala/Downloads";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/Games" = {
    device = "/persist/home/salivala/Games";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/Pictures" = {
    device = "/persist/home/salivala/Pictures";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/Projects" = {
    device = "/persist/home/salivala/Projects";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/Videos" = {
    device = "/persist/home/salivala/Videos";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home/salivala/nixos-config" = {
    device = "/persist/home/salivala/nixos-config";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/opt/wine-devel" = {
    device = "/persist/opt/wine-devel";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/var/cache/tuigreet/lastuser" = {
    device = "/cache/var/cache/tuigreet/lastuser";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/var/lib/libvirt" = {
    device = "/persist/var/lib/libvirt";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/var/lib/systemd/coredump" = {
    device = "/persist/var/lib/systemd/coredump";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/var/lib/zwift" = {
    device = "/persist/var/lib/zwift";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/var/tmp" = {
    device = "/cache/var/tmp";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/tmp" = {
    device = "zroot/tmp";
    fsType = "zfs";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/82467bcb-68f7-4666-b90e-7283f5041f89";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
