(require
  (prefix-in helix-discord-rpc. "helix-discord-rpc/helix-discord-rpc.scm"))
(helix-discord-rpc.discord-rpc-connect)
(require "scooter/scooter.scm")
(require "smooth-scroll/smooth-scroll.scm")
; (require "fake-warp/fake-warp.scm")
; (require "modeline/modeline.scm")
; (modeline-enable)
; (provide refresh-modeline)
(require "steel-pty/term.scm")
