include ~/.config/kitty/themes/noctalia.conf
include ~/.config/kitty/nix.conf

allow_remote_control yes
hide_window_decorations yes
enable_audio_bell no

tab_bar_style powerline
tab_bar_edge top

disable_ligatures cursor

shell_integration no-rc

window_margin_width 0
window_border_width 1
window_padding_width 0
draw_minimal_borders yes

enabled_layouts splits:split_axis=horizontal

map ctrl+shift+w close_window
map ctrl+shift+q close_window
map ctrl+shift+j neighboring_window down
map ctrl+shift+k neighboring_window up
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+alt+j move_window down
map ctrl+shift+alt+k move_window up
map ctrl+shift+alt+h move_window left
map ctrl+shift+alt+l move_window right
map ctrl+shift+enter launch --cwd=current --type=os-window
map ctrl+shift+n launch --cwd=current --type=window --location=split
map ctrl+shift+s launch --cwd=current --location=hsplit
map ctrl+shift+v launch --cwd=current --location=vsplit


# BEGIN_KITTY_FONTS
font_family      family="Cascadia Code NF"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
